"""Generate a simple PDF receipt from a receipt snapshot JSON."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from io import BytesIO
from typing import Any

from fpdf import FPDF


def _safe(value: Any, default: str = "-") -> str:
    if value is None or value == "":
        return default
    # Helvetica core fonts are latin-1 only
    return str(value).encode("latin-1", "replace").decode("latin-1")


def generate_receipt_pdf(
    *,
    receipt_number: str,
    issued_at: str,
    society_id: str,
    snapshot_json: str,
    brand_name: str = "Nivas",
) -> tuple[bytes, str]:
    try:
        snapshot = json.loads(snapshot_json) if snapshot_json else {}
    except json.JSONDecodeError:
        snapshot = {"raw": snapshot_json}

    bill = snapshot.get("bill") or {}
    payment = snapshot.get("payment") or {}

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(0, 12, brand_name or "Nivas", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, "Payment receipt", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    pdf.set_draw_color(40, 40, 40)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    issued = issued_at or datetime.now(timezone.utc).isoformat()
    rows = [
        ("Receipt number", receipt_number or "-"),
        ("Issued at", issued),
        ("Society ID", society_id or "-"),
        ("Bill", _safe(bill.get("title"))),
        ("Bill amount", f"{_safe(bill.get('currency'), 'INR')} {_safe(bill.get('amount'))}"),
        ("Paid amount", f"{_safe(bill.get('currency'), 'INR')} {_safe(payment.get('amount'))}"),
        ("Method", _safe(payment.get("method"))),
        ("Reference", _safe(payment.get("reference"))),
        ("Paid at", _safe(payment.get("paidAt"))),
        ("Payment ID", _safe(payment.get("uid"))),
        ("Bill ID", _safe(bill.get("uid"))),
    ]

    pdf.set_font("Helvetica", "", 11)
    for label, value in rows:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(50, 8, label)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 8, value)
        pdf.ln(1)

    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(
        0,
        5,
        "Generated by Nivas analytics. This document is a system receipt "
        "snapshot and not a tax invoice unless stamped by your society.",
    )

    buffer = BytesIO()
    pdf.output(buffer)
    filename = f"{(receipt_number or 'receipt').replace('/', '-')}.pdf"
    return buffer.getvalue(), filename
