FROM node:20-bookworm-slim AS build
WORKDIR /app
COPY package.json package-lock.json ./
COPY packages ./packages
COPY apps ./apps
RUN npm ci \
  && npm run build --workspace=service-realtime

FROM node:20-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV LOG_FORMAT=json
COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/packages ./packages
COPY --from=build /app/apps/service-realtime ./apps/service-realtime
WORKDIR /app/apps/service-realtime
EXPOSE 3003 50052
CMD ["node", "dist/index.js"]
